---
# These task will do the basic configuration for a dump1090 host.
# ted.sluis@gmail.com

# http://docs.ansible.com/ansible/cron_module.html

# cron jobs: weekly update & reboot
- name: schedule apt-get update & upgrade every cronjob friday 0am.
  cron: 
    name: "schedule apt-get update & upgrade every cronjob friday 0am."
    minute: "0"
    hour: "0"
    weekday: "5"
    job: "sudo apt-get update && sudo apt-get upgrade -y"
  become: true
- name: schedule reboot cronjob every friday 3am.
  cron:
    name: "schedule reboot cronjob every friday 3am."
    minute: "{{ rebootdelay }}"
    hour: "3"
    weekday: "5"
    job: "sudo /sbin/reboot"
  become: true



