---
# These task will install basic packages and do the basic configuration for a dump1090 host.
# ted.sluis@gmail.com

# http://docs.ansible.com/ansible/playbooks_roles.html

- include: packages.yml
- include: git.yml
- include: connectdumpsh.yml
- include: aliasses.yml
- include: vimsettings.yml
- include: etchosts.yml
- include: cronjobs.yml
- include: timezone.yml

