---
# These task will install basic packages and do the basic configuration for a dump1090 host.
# ted.sluis@gmail.com

# http://docs.ansible.com/ansible/apt_module.html

- name: Install basic packages
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
  - apt-utils 
  - cron 
  - curl
  - debhelper 
  - git
  - netcat 
  - net-tools 
  - nmap
  - python2.7 
  - rsync
  - scp
  - vim
  - wget
  become: true

# http://docs.ansible.com/ansible/lineinfile_module.html

- name: Insert alias ll into .profile
  lineinfile:
    dest: '/home/pi/.profile'
    regexp: '^alias ll='
    state: present
    line: 'alias ll="ls -ls --color"'
  become: true

- name: Set vim syntax no (globaly)
  lineinfile:
    dest: /etc/vim/vimrc
    regexp: '^"?syntax on'
    state: present
    line: 'syntax on'
  become: true

- name: Add /home/pi/connect.dump.sh to /etc/rc.local
  lineinfile:
    dest: /etc/rc.local
    regexp: '^/home/pi/connect.dump.sh'
    state: present
    insertbefore: '^exit 0'
    line: '/home/pi/connect.dump.sh &'
  become: true

- name: Update /etc/hosts from inventory
  lineinfile: dest=/etc/hosts 
    regexp='.*{{item}}$' 
    line='{{hostvars[item].ansible_default_ipv4.address}} {{item}}' 
    state=present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: '{{groups.all}}'
  tags:
    - hosts
  become: true
