---
# These task will do the basic configuration for a dump1090 host.
# ted.sluis@gmail.com

# https://docs.ansible.com/ansible/timezone_module.html

# Set time zone
- name: "set timezone to {{ mytimezone }}"
  timezone:
    name: "{{ mytimezone }}"
  become: true

