# Prepare, build, install and configure dump1090
# ted.sluis@gmail.com

- name: prepare for build dump1090
  hosts: all
  remote_user: pi
  roles:
  - dump1090-prepare

- name: clone from git & build dump1090
  hosts: all
  remote_user: pi
  roles:
  - dump1090-build

- name: install dump1090
  hosts: all
  remote_user: pi
  roles:
  - dump1090-install

- name: configure dump1090
  hosts: all
  remote_user: pi
  roles:
  - dump1090-configure
