- name: prepare for build dum1090
  hosts: ted1090-2
  remote_user: pi
  roles:
  - prepare-dump1090

- name: clone from git & build dump1090
  hosts: ted1090-2
  remote_user: pi
  roles:
  - build-dump1090

- name: install dump1090
  hosts: ted1090-2
  remote_user: pi
  roles:
  - install-dump1090

- name: configure dump1090
  hosts ted1090-2
  remote_user: pi
  roles:
  - configure-dump1090
