---
# These task will install dump1090-tools
# ted.sluis@gmail.com

# http://docs.ansible.com/ansible/get_url_module.html

# Download the dump1090-tools installer
- name: "Download the dump1090-tools installer."
  get_url: 
    url: "https://raw.githubusercontent.com/tedsluis/dump1090-tools/master/dump1090-tools-install.sh" 
    dest: "/tmp/dump1090-tools-install.sh"
    mode: 0555
    force: yes
  become: true

# Install dump1090-tools
- name: "Install dump1090-tools (this will take a while!)."
  shell: "/tmp/dump1090-tools-install.sh"



