---
# These task will install all packages for building and running dump1090
# ted.sluis@gmail.com

# http://docs.ansible.com/ansible/get_url_module.html

# Download the rtl-sdr packages
- name: Download rtl-sdr arm packages
  get_url: 
    url: "https://github.com/mutability/librtlsdr/releases/download/v0.5.4_git-1/{{ item }}" 
    dest: "/tmp/{{ item }}"
    mode: 0440
    force: yes
  with_items:
  - librtlsdr0_0.5.4.git-1_armhf.deb                                                                       
  - librtlsdr-dev_0.5.4.git-1_armhf.deb                                                                       
  - rtl-sdr_0.5.4.git-1_armhf.deb
  become: true

# http://docs.ansible.com/ansible/apt_module.html

# Install packages 
- name: Install packages for basis dump1090 & dump-tools host
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
  - apt-utils 
  - build-essential 
  - ca-certificates 
  - cron 
  - curl
  - debhelper 
  - dialog 
  - dpkg-dev 
  - git
  - librtlsdr-dev 
  - librtlsdr0 
  - libpython2.7
  - libusb-1.0-0-dev 
  - lighttpd 
  - pkg-config 
  - python2.7 
  - rtl-sdr 
  - wget
  become: true

- name: Install rtl-sdr arm packages
  apt: deb=/tmp/{{ item }}
  with_items:
  - rtl-sdr_0.5.4.git-1_armhf.deb
  - librtlsdr-dev_0.5.4.git-1_armhf.deb 
  - librtlsdr0_0.5.4.git-1_armhf.deb  
  become: true
  
- name: Refresh cache
  apt: update_cache=yes
  become: true

- name: Upgrade all packages to the latest version
  apt: upgrade=full
  become: true

